image_width: 1440
image_height: 1080
pixel_format: bgr8
camera_info_url: 'file:///home/dynamicx/.ros/camera_info/hk_camera_8mm.yaml'
camera_name: hk_camera
camera_frame_id: camera_optical_frame
frame_id: camera_optical_frame
camera_sn: 00L28498183
#如果相机类型是ca016，camera_sn前要加00
frame_rate: 200
exposure_auto: false
exposure_value: 1500
exposure_value_windmill: 3000
gamma_selector: 2
gamma_value: 0.5
enable_imu_trigger: false
gain_auto: false
gain_value: 16
is_fps_down: false
target_fps: 15.0
